const actionTypes = {
    GET_HOME: "GET_HOME",
    SET_CURRENT_SONG_ID: "SET_CURRENT_SONG_ID",
    SET_CURRENT_SONG_INFO:"SET_CURRENT_SONG_INFO",
    SET_PLAYLIST:"SET_PLAYLIST",
    SET_PLAYLIST_ID:"SET_PLAYLIST_ID",
    PUSH_LISTEN_HISTORY : "PUSH_LISTEN_HISTORY",
    PLAY: "PLAY",
    REPEAT:"REPEAT",
    LOAD:"LOAD",
    SET_VOLUME:"SET_VOLUME",
    MUTE_VOLUME: "MUTE_VOLUME",
    SEARCH:"SEARCH",
    SEARCH_SONGS_ARTIST:"SEARCH_SONGS_ARTIST",
    SET_CURRENT_WIDTH: "SET_CURRENT_WIDTH",
    SET_SEARCH_ID: "SET_SEARCH_ID",
};
export default actionTypes;
